name: SonarCloud Analysis
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
 
      # --- NUEVO PASO AÑADIDO ---
      - name: Create sonar-project.properties
        run: |
          echo "sonar.organization=federico1605" >> sonar-project.properties
          echo "sonar.projectKey=federico1605_CentralizadorBackEnd" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties
 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}